package com.sample
 
import com.sample.DroolsTest.Message;
import entity.Patient;
global java.util.List myInfo;
 
rule "age"
	activation-group "patient"
	lock-on-active
	salience 10
	no-loop
    when
        $patient : Patient(age >= 75)
    then
    	$patient.setPatientType(Patient.OLD_PATIENT);
        System.out.println("高龄高血压患者");
        update( $patient );
end

rule "gender"
	activation-group "patient"
	lock-on-active
	salience 9
	no-loop
    when
        $patient : Patient(age < 75 && pci == 1)
    then
    	$patient.setPatientType(Patient.PCI_PATIENT);
        System.out.println( "pci冠心病患者" );
        update( $patient );
end

rule "gender2"
	activation-group "patient"
	lock-on-active
	salience 8
	no-loop
    when
        $patient : Patient(age < 75 && pci == 0)
    then
    	$patient.setPatientType(Patient.ORDINARY_PATIENT);
        System.out.println( "普通冠心病患者" );
        update( $patient );
end