package com.sample
 
import com.sample.DroolsTest.Message;
import entity.Patient;
import entity.Ball;
global java.util.List myInfo;
 

rule "gender11"
	activation-group "ball"
	lock-on-active
	salience 0
	//no-loop
    when
        $ball : Ball(a==0)
    then
        System.out.println( "a==0" );
        update($ball);
end

rule "gender12"
	activation-group "ball"
	lock-on-active
	salience 1
	//no-loop
    when
        $ball : Ball(b==0)
    then
        System.out.println( "b==0" );
        $ball.b=9;
        System.out.println($ball.b);
        update($ball);
end

rule "gender13"
	activation-group "ball"
	lock-on-active
	salience 2
	//no-loop
    when
        $ball : Ball(c==0)
    then
        System.out.println( "c==0" );
        update($ball);
end

rule "wtt"
	salience 3
	no-loop
	when 
		Ball()
	then
		System.out.println("wwwww");
end

rule "wtt2"
	salience 2
	when 
		Ball()
	then
		System.out.println("wwwww22");
end

rule "wt32"
	salience -2
	when 
		Ball(b==9)
	then
		System.out.println("wwwwwwwwwwww");
end